# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[cmake]
version = "3.25"

[project]
name = "zyemu"

[subdir.thirdparty]

[target.zyemu]
type = "static"
alias = "zyemu::zyemu"
sources = [
    "src/zyemu/assembler.cpp",
    "src/zyemu/codecache.cpp",
    "src/zyemu/codegen.cpp",
    "src/zyemu/cpu.cpp",
    "src/zyemu/platform.cpp",
    "src/zyemu/registers.cpp",
]
headers = [
    "include/zyemu/types.hpp",
    "include/zyemu/zyemu.hpp",
    "src/zyemu/assembler.hpp",
    "src/zyemu/codecache.hpp",
    "src/zyemu/codegen.hpp",
    "src/zyemu/internal.hpp",
    "src/zyemu/platform.hpp",
    "src/zyemu/registers.hpp",
]
include-directories = ["include"]
compile-features = ["cxx_std_23"]
link-libraries = ["Zydis", "sfl::sfl"]
msvc.private-compile-options = ["/MP", "$<$<CONFIG:Release>:/Oi>"]
private-link-options = ["$<$<CONFIG:Release>:/DEBUG>"]

[target.zyemu-playground]
type = "executable"
sources = [
    "src/playground/main.cpp"
]
compile-features = ["cxx_std_23"]
private-link-libraries = ["zyemu::zyemu"]
private-link-options = ["$<$<CONFIG:Release>:/DEBUG>"]

[target.zyemu-tests]
type = "executable"
sources = [
    "src/tests/main.cpp",
    "src/tests/testdata.cpp",
    "src/tests/tests/emulation.cpp",
    "src/tests/tests/emulation.testdata.cpp",
    "src/tests/tests/registers.cpp",
]
headers = [
    "src/tests/testdata.hpp",
    "src/tests/tests/memory.hpp",
]
private-include-directories = ["src/tests", "src/zyemu"]
compile-features = ["cxx_std_23"]
msvc.private-compile-options = ["/MP", "$<$<CONFIG:Release>:/Oi>"]
private-link-libraries = ["zyemu::zyemu", "GTest::gtest"]
private-link-options = ["$<$<CONFIG:Release>:/DEBUG>"]